// Generated by tools/sync-game-tables.mjs from src/data. Do not edit by hand.
export const WHEEL_ORDER = [0,32,15,19,4,21,2,25,17,34,6,27,13,36,11,30,8,23,10,5,24,16,33,1,20,14,31,9,22,18,29,7,28,12,35,3,26];
export const TIER_BETS: { id: string; numbers: number; multiplier: number }[] = [{"id":"common","numbers":24,"multiplier":1.5},{"id":"uncommon","numbers":18,"multiplier":2},{"id":"rare","numbers":12,"multiplier":3},{"id":"epic","numbers":8,"multiplier":4.5},{"id":"legendary","numbers":6,"multiplier":6},{"id":"mythic","numbers":4,"multiplier":9},{"id":"exotic","numbers":3,"multiplier":10}];
export const CHIPS = [5,10,25,50,100];
export const TABLE_LIMIT = 1000;
export const RETURNS: Record<string, number> = {"straight":36,"color":2,"parity":2,"half":2,"dozen":3,"column":3};
