// Generated by tools/sync-game-tables.mjs from src/data. Do not edit by hand.
export const SYMBOL_IDS = ["page","book","globe","star","wiki"];
export const REEL: string[] = ["page","page","page","page","page","page","page","page","page","page","book","book","book","book","book","book","globe","globe","globe","globe","star","star","wiki"];
export const PAYLINES: { id: string; rows: number[] }[] = [{"id":"top","rows":[0,0,0]},{"id":"middle","rows":[1,1,1]},{"id":"bottom","rows":[2,2,2]},{"id":"down","rows":[0,1,2]},{"id":"up","rows":[2,1,0]}];
export const PAYTABLE: Record<string, Record<number, number>> = {"page":{"2":0.5,"3":4.25},"book":{"2":1.25,"3":10},"globe":{"2":2,"3":30},"star":{"3":100},"wiki":{"3":400}};
export const LINE_BETS = [2,5,10,25,50];
